name: Run lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  golangci:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-go@v5.5.0
        with:
          go-version: 1.25
          # We don't need cache when there are no dependencies
          cache: false

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8.0.0
        with:
          only-new-issues: true
